# Generated by Django 3.2.7 on 2021-10-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aikido_Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('region', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('club', models.CharField(max_length=30)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('isTrainer', models.BooleanField()),
                ('trainer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'aikido_member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Seminar'), ('1', 'Competition')], max_length=11)),
                ('participants', models.JSONField()),
            ],
            options={
                'db_table': 'applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('club', models.CharField(max_length=30, verbose_name='club')),
                ('trainer', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('attestation_date', models.DateField()),
                ('oldKu', models.IntegerField(null=True, verbose_name='oldKu')),
                ('newKu', models.IntegerField(null=True, verbose_name='newKu')),
                ('isChild', models.BooleanField(verbose_name='isChild')),
                ('examiner', models.CharField(max_length=100, verbose_name='examiner')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PersonalArea.aikido_member')),
            ],
            options={
                'db_table': 'seminars',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('club', models.CharField(max_length=30, verbose_name='club')),
                ('trainer', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('position', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PersonalArea.aikido_member')),
            ],
            options={
                'db_table': 'competitions',
                'managed': True,
            },
        ),
    ]
