# Generated by Django 3.2.7 on 2021-11-06 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_record_date', models.DateField(default=datetime.date.today)),
                ('end_record_date', models.DateField(default=datetime.date.today)),
                ('date_of_event', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(default='None', max_length=30)),
                ('responsible_club', models.CharField(default='None', max_length=30)),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aikido_Member',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('region', models.IntegerField()),
                ('club', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('isTrainer', models.BooleanField(blank=True, default=False)),
                ('trainer_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'aikido_member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=30, verbose_name='club')),
                ('trainer', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('attestation_date', models.DateField()),
                ('start_date', models.DateField()),
                ('oldKu', models.IntegerField(null=True, verbose_name='oldKu')),
                ('newKu', models.IntegerField(blank=True, default=None, null=True, verbose_name='newKu')),
                ('isChild', models.BooleanField(verbose_name='isChild')),
                ('examiner', models.CharField(max_length=100, verbose_name='examiner')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seminar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=25)),
                ('surname', models.CharField(default='None', max_length=25)),
                ('second_name', models.CharField(blank=True, default='None', max_length=25)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('trainer_id', models.IntegerField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='PersonalArea.events')),
            ],
            options={
                'db_table': 'request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('name', models.CharField(default='unable', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('region', models.IntegerField()),
                ('club', models.CharField(max_length=30, verbose_name='club')),
                ('trainer', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('position', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competition',
                'managed': True,
            },
        ),
    ]
