# Generated by Django 3.2.7 on 2021-10-18 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_record_date', models.DateField(default=django.utils.timezone.now)),
                ('end_record_date', models.DateField(default=django.utils.timezone.now)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('0', 'Seminar'), ('1', 'Competition')], max_length=20)),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.IntegerField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PersonalArea.events')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PersonalArea.aikido_member')),
            ],
            options={
                'db_table': 'request',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
