# Generated by Django 3.2.7 on 2021-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aikido_member',
            name='isAdmin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='aikido_member',
            name='login',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, unique=True),
        ),
    ]
