# Generated by Django 3.2.7 on 2021-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='trainer_id',
            field=models.IntegerField(null=True),
        ),
    ]
