# Generated by Django 3.2.7 on 2021-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aikido_member',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='region',
        ),
        migrations.AlterField(
            model_name='aikido_member',
            name='isTrainer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='aikido_member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aikido_member',
            name='trainer_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
