# Generated by Django 3.2.7 on 2021-10-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0002_alter_aikido_member_trainer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='student_id',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='student_id',
            new_name='member_id',
        ),
    ]
