# Generated by Django 3.2.7 on 2022-04-01 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('attestation_date', models.DateField()),
                ('received_ku', models.IntegerField(null=True)),
                ('is_child', models.BooleanField()),
            ],
            options={
                'db_table': 'event_name',
                'get_latest_by': 'attestation_date',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='aikido_member',
            name='login',
        ),
        migrations.DeleteModel(
            name='Seminar',
        ),
        migrations.AddField(
            model_name='achievements',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
