# Generated by Django 3.2.7 on 2022-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='coordinates',
            field=models.TextField(),
        ),
    ]
