# Generated by Django 3.2.7 on 2022-03-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
