# Generated by Django 3.2.7 on 2021-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0002_auto_20211028_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='newKu',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='newKu'),
        ),
    ]
