# Generated by Django 3.2.7 on 2022-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0003_auto_20220403_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='aikido_member',
            name='is_main_trainer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
