# Generated by Django 3.2.7 on 2021-10-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0003_alter_seminar_newku'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='request',
            name='second_name',
            field=models.CharField(blank=True, default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='request',
            name='surname',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='request',
            name='member_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PersonalArea.aikido_member'),
        ),
    ]
