# Generated by Django 3.2.7 on 2022-04-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0003_auto_20220401_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievements',
            table='achievements',
        ),
    ]
