# Generated by Django 3.2.7 on 2021-11-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0003_auto_20211110_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aikido_member',
            name='isAdmin',
        ),
        migrations.AlterField(
            model_name='aikido_member',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
