# Generated by Django 3.2.7 on 2021-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0003_auto_20211008_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
