# Generated by Django 3.2.7 on 2022-04-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('PersonalArea', '0004_alter_achievements_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='responsible_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_club', to='clubs.club'),
        ),
    ]
