# Generated by Django 3.2.7 on 2021-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0004_auto_20211110_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='aikido_member',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
