# Generated by Django 3.2.7 on 2021-11-20 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0005_aikido_member_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_of_event',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='events',
            name='responsible_trainer',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_record_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_record_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
