# Generated by Django 3.2.7 on 2021-10-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0005_events_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PersonalArea.aikido_member'),
        ),
    ]
