# Generated by Django 3.2.7 on 2022-04-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_main_trainers'),
        ('PersonalArea', '0005_alter_aikido_member_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
    ]
