# Generated by Django 3.2.7 on 2021-10-30 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0006_alter_request_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
