# Generated by Django 3.2.7 on 2021-11-29 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0006_auto_20211120_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'get_latest_by': 'attestation_date', 'managed': True},
        ),
        migrations.AlterField(
            model_name='seminar',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
