# Generated by Django 3.2.7 on 2022-04-08 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0006_alter_aikido_member_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='event_name',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
