# Generated by Django 3.2.7 on 2022-04-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0006_rename_event_name_request_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='event',
            new_name='event_name',
        ),
    ]
