# Generated by Django 3.2.7 on 2022-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0007_auto_20220408_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aikido_member',
            name='region',
        ),
        migrations.AddField(
            model_name='aikido_member',
            name='city',
            field=models.CharField(default='Екатеринбург', max_length=50),
        ),
    ]
