# Generated by Django 3.2.7 on 2021-11-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0007_auto_20211129_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
