# Generated by Django 3.2.7 on 2021-10-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0008_auto_20211030_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_id', to='PersonalArea.aikido_member'),
        ),
    ]
