# Generated by Django 3.2.7 on 2022-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0008_alter_seminar_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(default='None', max_length=150),
        ),
    ]
