# Generated by Django 3.2.7 on 2022-03-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('PersonalArea', '0009_events_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
