# Generated by Django 3.2.7 on 2021-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0009_alter_request_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
