# Generated by Django 3.2.7 on 2022-03-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_main_trainers'),
        ('PersonalArea', '0010_auto_20220331_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='club',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='events',
            name='responsible_club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_club', to='clubs.club'),
        ),
    ]
