# Generated by Django 3.2.7 on 2022-03-31 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0011_auto_20220331_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_record_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_record_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
