# Generated by Django 3.2.7 on 2022-03-31 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_main_trainers'),
        ('PersonalArea', '0012_auto_20220331_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='responsible_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_club', to='clubs.club'),
        ),
    ]
