# Generated by Django 3.2.7 on 2021-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0015_rename_event_request_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aikido_member',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
