# Generated by Django 3.2.7 on 2021-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0016_aikido_member_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
