# Generated by Django 3.2.7 on 2021-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalArea', '0017_alter_aikido_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikido_member',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
