# Generated by Django 3.2.7 on 2022-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
