# Generated by Django 3.2.7 on 2022-04-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_main_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo_images/'),
        ),
    ]
